### ISSUE TITLE
Add HOP token

### ISSUE THREAD

**Issue by litodertechie** [albertocevallos/token-icons#1]
![hop_logo](https://user-images.githubusercontent.com/30246668/197100260-ffe0e27e-7abc-4235-8445-041beac29de1.png)

**Comment by yosefcevallos** [comment]
Just added it in this commit:
https://github.com/albertocevallos/token-icons/tree/main/assets/blockchains/ethereum/assets/0xc5102fE9359FD9a28f877a67E36B0F050d81a3CC

Should be live on the [tokenicons.org](https://tokenicons.org).
